name: Build Docker image and download

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile Java file
        run: javac HelloWorld.java

      - name: Create JAR
        run: jar cfe HelloWorld.jar HelloWorld HelloWorld.class

      - name: Build Docker image
        run: docker build -t my-java-app:${{ github.sha }} .

      - name: Save Docker image as tar
        run: docker save my-java-app:${{ github.sha }} -o my-java-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app-docker-image
          path: my-java-app.tar
          retention-days: 7

      - name: Test Docker container
        run: docker run my-java-app:${{ github.sha }}
