name: example workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: greet the user
        run:  
          echo "Hello world"

        
