name: example workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  variables_job:
    needs: 
      - second_job
      - first_job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "repo variable check ${{vars.VAR1}}"
          echo "repo variable ${{vars.REPO_VAR}}"
          echo "${{secrets.AWS_KEY}}"
    environment: prods
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Hello world" 
            echo "hello world 2"
            echo "hello world from ${{github.actor}} ${{github.repository}}"
            echo "${{github.ref}}"
        - run: |
            echo "1st step"
            echo "hello world from ${{github.actor}} ${{github.repository}}"

        - run: echo "2nd step"
  second_job:
    name: second job
    runs-on:  ubuntu-latest
    steps:
      - name: greet the user using 2nd job
        run: echo "hello fronm 2nd job"
      - uses: actions/checkout@v4.1.0
      - run: tree

        
