name: example workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: greet the user
        run:  |
          echo "Hello world" 
          echo "hello world 2"
          echo "hello world from ${{github.actor}} ${{github.repository}}"
        
        shell: bash
        run:  |
          echo "2nd step"
  second_job:
    name: second job
    runs-on:  ubuntu-latest
    steps:
      - name: greet the user using 2nd job
        run: echo "hello fronm 2nd job"

        
