name: Pull Request Checks

on:
  - pull_request
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Workflow triggered by a pull request"
